# Generated by Django 3.2.4 on 2024-11-19 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_usuarios_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='correo',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='api.rol'),
        ),
        migrations.CreateModel(
            name='Publicaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(null=True)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('requisitos', models.TextField(null=True)),
                ('estado', models.BooleanField()),
                ('reclutador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publicaciones', to='api.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='EtapaMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(null=True)),
                ('observaciones', models.TextField(null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('publicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etapa_media', to='api.publicaciones')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etapa_media', to='api.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='EtapaInicial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(null=True)),
                ('observaciones', models.TextField(null=True)),
                ('publicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etapa_inicial', to='api.publicaciones')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etapa_inicial', to='api.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='EtapaFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(null=True)),
                ('observaciones', models.TextField(null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('retroalimentacion', models.TextField(null=True)),
                ('publicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etapa_final', to='api.publicaciones')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etapa_final', to='api.usuarios')),
            ],
        ),
    ]
