# Generated by Django 3.2.4 on 2024-11-22 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_usuarios_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapafinal',
            name='estado',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='etapainicial',
            name='estado',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='etapamedia',
            name='estado',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='publicaciones',
            name='estado',
            field=models.CharField(max_length=255),
        ),
    ]
