# Generated by Django 5.1.3 on 2024-11-23 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_usuarios_apellido_usuarios_celular_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicaciones',
            name='candidato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publicaciones_candidato', to='api.usuarios'),
        ),
    ]
