# Generated by Django 5.1.3 on 2024-11-28 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_publicaciones_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicaciones',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='correo',
            field=models.EmailField(max_length=255),
        ),
    ]
